// Builds privacy/index.html from PRIVACY.md, in the site's own look:
//   node scripts/privacy-page.mjs
// PRIVACY.md stays the source of truth (the stores and the extension link to it), so rerun
// this after any change to the policy. It understands the markdown the policy uses:
// headings, paragraphs, a table, **bold**, `code`, [links](url), bare URLs and emails.
import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'

const md = readFileSync('PRIVACY.md', 'utf8').replace(/\r/g, '')

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
const inline = (s) => esc(s)
  .replace(/`([^`]+)`/g, '<code>$1</code>')
  .replace(/\*\*([^*]+)\*\*/g, '<b>$1</b>')
  .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2">$1</a>')
  .replace(/(^|[\s(])(https?:\/\/[^\s<)]+)/g, '$1<a href="$2">$2</a>')
  .replace(/(^|\s)([\w.+-]+@[\w-]+\.[\w.]+)/g, '$1<a href="mailto:$2">$2</a>')
const slug = (s) => s.toLowerCase().replace(/^\d+\.\s*/, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')

let title = ''
let meta = ''
const toc = []
const body = []
for (const block of md.split(/\n{2,}/)) {
  const text = block.trim()
  if (!text) continue
  if (text.startsWith('# ')) {
    title = text.slice(2)
  } else if (text.startsWith('## ')) {
    const h = text.slice(3)
    const id = slug(h)
    toc.push(`<li><a href="#${id}">${esc(h)}</a></li>`)
    body.push(`<h2 id="${id}">${esc(h)}</h2>`)
  } else if (text.startsWith('|')) {
    const rows = text.split('\n').filter((r) => !/^\|\s*-/.test(r)).map((r) => r.slice(1, -1).split('|').map((c) => c.trim()))
    const [head, ...rest] = rows
    body.push(`<table><thead><tr>${head.map((c) => `<th>${inline(c)}</th>`).join('')}</tr></thead><tbody>${
      rest.map((r) => `<tr>${r.map((c) => `<td>${inline(c)}</td>`).join('')}</tr>`).join('')}</tbody></table>`)
  } else if (!meta && text.startsWith('**Effective date')) {
    meta = text.split('\n').map(inline).join('<br>')
  } else {
    body.push(`<p>${inline(text.replace(/\n/g, ' '))}</p>`)
  }
}

const mark = '<svg class="mark" viewBox="0 0 28 16" aria-hidden="true"><rect x=".5" y=".5" width="27" height="15" rx="7.5"/><circle cx="20" cy="8" r="5"/></svg>'
const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Privacy · Dumbify</title>
<meta name="description" content="Dumbify collects no information. It runs entirely in your browser, with no server, no analytics and no account.">
<meta name="theme-color" content="#0a0a0a">
<link rel="canonical" href="https://edenrebello.me/dumbify/privacy/">
<link rel="icon" type="image/png" sizes="32x32" href="../public/icons/icon-32.png">
<link rel="stylesheet" href="../site/site.css">
<!-- Generated by scripts/privacy-page.mjs from PRIVACY.md. Edit the markdown, not this file. -->
</head>
<body>
<a class="skip" href="#policy">Skip to content</a>
<header class="nav-wrap">
  <nav class="nav wrap" aria-label="Main">
    <a class="brand" href="../" aria-label="Dumbify home">${mark}<span>dumbify</span></a>
    <div class="nav-end">
      <a class="nav-text" href="https://github.com/edenreb/dumbify">GitHub</a>
      <a class="pill pill-light pill-sm" href="../">Back to Dumbify</a>
    </div>
  </nav>
</header>

<main class="legal wrap" id="policy" tabindex="-1">
  <header class="legal-head">
    <p class="legal-kicker">Privacy</p>
    <h1>${esc(title.replace(/ for Dumbify$/, ''))}</h1>
    <p class="legal-lede">Dumbify collects no information. It runs entirely in your browser, with no server, no analytics and no account.</p>
    <p class="legal-meta">${meta}</p>
  </header>
  <div class="legal-grid">
    <nav class="legal-toc" aria-label="Sections"><p>On this page</p><ol>${toc.join('')}</ol></nav>
    <article class="legal-body">
${body.map((b) => '      ' + b).join('\n')}
    </article>
  </div>
</main>

<footer class="foot wrap">
  <div>
    <a class="brand" href="../" aria-label="Dumbify home">${mark}<span>dumbify</span></a>
    <p>YouTube, without the noise.<br>Made by Eden Rebello and Gabriel Tan. Not affiliated with YouTube or Google.</p>
  </div>
  <nav aria-label="Footer">
    <a href="https://chromewebstore.google.com/detail/dumbify-customizable-text/lhnjjldhbllcdfdldeacdgalkkofhicf">Chrome Web Store</a>
    <a href="https://addons.mozilla.org/en-US/firefox/addon/dumbify/">Firefox Add-ons</a>
    <a href="https://github.com/edenreb/dumbify">GitHub</a>
    <a href="https://github.com/edenreb/dumbify/blob/main/PRIVACY.md">Policy source</a>
  </nav>
</footer>
<script src="../site/trail.js" type="module"></script>
</body>
</html>
`
mkdirSync('privacy', { recursive: true })
writeFileSync('privacy/index.html', html)
console.log(`privacy/index.html: ${toc.length} sections`)
